IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = '{{SCHEMA_NAME}}')
    EXEC(N'CREATE SCHEMA [{{SCHEMA_NAME}}]');

IF OBJECT_ID(N'[{{SCHEMA_NAME}}].[{{MIGRATIONS_TABLE}}]', N'U') IS NULL
BEGIN
    CREATE TABLE [{{SCHEMA_NAME}}].[{{MIGRATIONS_TABLE}}]
    (
        [MigrationId] NVARCHAR(50) NOT NULL PRIMARY KEY,
        [Description] NVARCHAR(200) NOT NULL,
        [AppliedAt] DATETIME2 NOT NULL CONSTRAINT [DF_{{MIGRATIONS_TABLE}}_AppliedAt] DEFAULT SYSUTCDATETIME()
    );
END;

IF OBJECT_ID(N'[{{SCHEMA_NAME}}].[{{STATE_TABLE}}]', N'U') IS NULL
BEGIN
    CREATE TABLE [{{SCHEMA_NAME}}].[{{STATE_TABLE}}]
    (
        [StateKey] NVARCHAR(100) NOT NULL PRIMARY KEY,
        [Payload] NVARCHAR(MAX) NOT NULL,
        [UpdatedAt] DATETIME2 NOT NULL
    );
END;
